### ISSUE TITLE
Dropped support for createCachedSelector calls with multiple arguments?

### ISSUE THREAD

**Issue by mrlubos** [toomuchdesign/re-reselect#128]
### Do you want to request a _feature_ or report a _bug_?

Question

### What is the current behaviour?

Why was the support for calling `createCachedSelector()` with multiple arguments dropped and what exactly does this mean?

### What is the expected behaviour?

N/A

### Steps to Reproduce the Problem

N/A

### Specifications

N/A

**Comment by toomuchdesign** [comment]
Hi @mrlubos,
until version `v3.3.0`, options had to be provided through an extra argument after `keySelector`:

```js
createCachedSelector(
  // ...
)(
  keySelector, { options }
)
```
Version `v3.4.0` introduced the possibility of providing a single `keySelector` for simple cases or a single `options` object (accepting a `keySelector` entry) to get full powers.

```js
createCachedSelector(
  // ...
)(
  keySelector | { options }
)
```

From `v4.0.0` this became the only way to call `createCachedSelector`.

This means that -in complex scenarios- instead of providing a `keySelector` and an `options` object you have to provide just an `options` object with a `keySelector` entry.

If you wanted to uniform your `createCachedSelector` calls, use always the `options` object.

```js
createCachedSelector(
  // ...
)(
  {
    keySelector
  }
)
```

**Comment by fregadev** [comment]
I came here precisely for that explanation! Thanks @toomuchdesign 

Maybe it could be restated as "Dropped support for `createCachedSelector(...)(arguments)` calls with multiple `arguments`" or something like that? The original statement is very confusing.

**Comment by mrlubos** [comment]
Thank you for the explanation @toomuchdesign!
