### ISSUE TITLE
Boolean cannot be memorized

### ISSUE THREAD

**Issue by yellowfrogCN** [toomuchdesign/re-reselect#19]
```jsx
const getSelectedCls = createCachedSelector(
    props => props.a === props.b,
    bol => {
        // Do what I want to do
    }
)(
    props => props.a === props.b
)
getSelectedCls(props); // There is no work
```

**Comment by yellowfrogCN** [comment]
0 ，‘0’  cannot be memorized too！

**Comment by toomuchdesign** [comment]
Hi @yellowfrogCN,
the `resolverFunction` not accepting booleans is actually an expected behaviour dued to the very simple implementation of the resolver function. From the [docs](https://github.com/toomuchdesign/re-reselect/tree/v0.6.2#rereselectreselects-createselector-argumentsresolverfunction-selectorcreator--selectorcreator):

> resolverFunction is a function which receives the same arguments of your selectors (and inputSelectors) and must return a string or number. The result is used as cache key to store/retrieve selector instances.

It should accept `0` or `"0"`, instead. Would you be able to reproduce the issue with those values?

Thank you, cheers!

**Comment by toomuchdesign** [comment]
I wasn't able to reproduce the wrong behaviour returning `"0"` or `0` from the resolver function.
I close the issue for the moment.

@yellowfrogCN please feel free to re-open the thread if I'm missing something.
