### ISSUE TITLE
Debugging cache

### ISSUE THREAD

**Issue by oyeanuj** [toomuchdesign/re-reselect#32]
Hi @toomuchdesign, thank you for creating this library! I was wondering if there are any recommendations around debugging selectors to make sure that the cache is working, and to see what might be causing changes?

I came across https://github.com/kbrownlees/reselect-change-memoize and was wondering if you've considered a similar utility for `re-reselect` which provides callback when new objects are added to cache or when something is used from cache?

**Comment by toomuchdesign** [comment]
Hi @oyeanuj!
I've never stepped into this specific need.

Since you'd like to **extend cache functionality**, I would suggest as a first try to **extend the default cache objects** with the desired behaviour.

`re-reselect` cache logic is completely **pluggable** by providing a `cacheObject` with a [given interface](https://github.com/toomuchdesign/re-reselect#optionscacheobject).

**Cache objects** are just **ES6 classes** ready [to be extended](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Sub_classing_with_extends) like this:

```js
import { FlatCacheObject  } from re-reselect;

class ExtendedFlatCacheObject extends FlatCacheObject {
  // Extending set method
  set(key, selectorFn) {
    // Any callback/extending behaviour, here...

    // Call parent method ;-)
    super.set(key, selectorFn);
  }
}
```

...and then plugged into a `re-reselect` selector through [`cacheObject` option](https://github.com/toomuchdesign/re-reselect#optionscacheobject):

```js
createCachedSelector(
  // ...
)(
  // resolverFunction,
  {
    cacheObject: new ExtendedFlatCacheObject(),
  }
) 
```
Does this approach fit your use case?

**Comment by oyeanuj** [comment]
@toomuchdesign Thanks, that should probably work. Once I try it, I'll report back. I wonder if other users will find this useful as a default option in the library?

**Comment by toomuchdesign** [comment]
Fill free to comment if the issue needed to be re-opened.
