### ISSUE TITLE
Null cache key automatically returns undefined

### ISSUE THREAD

**Issue by ethanroday** [toomuchdesign/re-reselect#43]
### Do you want to request a *feature* or report a *bug*?
Not so much a bug as an unexpected behavior.

### What is the actual behavior?
Using the default cache strategy, calling a selector with arguments that result in a `null` cache key will cause the selector to short-circuit and return `undefined`, totally circumventing the actual selector code. A warning is printed to the console noting that `null` is an invalid cache key.

### What is the expected behaviour?
I would expect to be able to handle a `null` value in the body of my selector, but I can't. This is particularly pernicious when I'm already returning non-undefined default values (e.g. an empty list) in error cases and assuming the default value's properties (e.g. calling `map` on the result of the selector function).

### Steps to Reproduce the Problem
Example code:

```js
const getCollectionById = createCachedSelector(
  state => state.collections,
  (state, collectionId) => collectionId,
  (collections, collectionId) => collections[collectionId] || []
)((state, collectionId) => collectionId);
// ...
// state is { collections: { a: ['thing1', 'thing2'] } }
const yellCollection = id => getCollectionById(state, id).map(thing => thing.toUpperCase());
const yelledB = yellCollection("b"); // expect [], but get an error for trying to map undefined
```
### Possible solutions

- Allow a **default value** as an option when cache keys are 'malformed' (at the selector level, not the strategy level)
- Just **execute the selector anyway** when cache keys are 'malformed'
- Let **`null` be an eligible cache key** in the default cache strategy (it's a little icky, but it _does_ work)

**Comment by toomuchdesign** [comment]
Hi @ethanroday,
I'm not sure whether your issue is originated by a typo or not.

If I get correctly the example above, `yellCollection` won't work since `getCollectionById` is called with a single argument while it expects `state` and `collectionId`.

**Default value** in case of invalid cacheKey can be implemented after selector call:
```js
const yellCollection = id => {
  const result = getCollectionById(state, id) || [];
  return result.map(thing => thing.toUpperCase());
}
```
_Please note that `.map` will return a new array on each call, nullifying the the advantage of returning the same object in case the consuming application relied on object immutability._

In order to **execute the selector anyway** when cacheKey is not valid you might:
- extend default `FlatObjectCache` overriding its `isValidCacheKey` method to always return `true`
- use any "Map" cache which accept any cache key

Did I miss any point?
Cheers!

**Comment by ethanroday** [comment]
Fixed the issue in my example - you are correct that I just forgot the `state` argument when calling 😅  
Regardless, that was just an illustration. To your points:
 - Using the `|| []` syntax is fine, but it would be nice to avoid since it's an easy thing to forget.
 - If, in your view, it's too much of an edge case to handle in the default cache strategy, I will just switch to the `FlatMapCache` per your suggestion.

Thanks for the detailed response!
