### ISSUE TITLE
Discussions on the project

### ISSUE THREAD

**Issue by augnustin** [toomuchdesign/re-reselect#44]
Hi @toomuchdesign 

Thanks again for pinging me about re-reselect on [SO](https://stackoverflow.com/a/51153516/1620081).

I have implemented it in my app super easily.

I have a few points I'd be happy to discuss with you though (sorry I removed you issue layout):

- the syntax is `createCachedSelector(regularSelector)(keySelector)`. I'd find it more natural if it were `createCachedSelector(keySelector)(regularSelector)` as `createCachedSelector(keySelector)` would become the smarter `createSelector` from `reselect`. What do you think? I know this would be a breaking change so it might not be possible in a near future, but at least it would have been discussed. :smile: 

- the `keySelector` syntax is `(state, otherParams) => {}`. But I reckon I never used the `state` params here. Isn't the selector supposed to be recalculated if the state changes, hence it shouldn't be part of the key parameters, should it? Hence, shouldn't it be instead:

```
createCachedSelector(
  (state, id) => state.data.collection,
  (state, id) => id,
  (collection, id) => collection.find(c => c.id === id)
)(id => id)
```

- finally I have cases where the selector doesn't hang on any extra parameter. For now, the syntax I have been using is:

```
export default createCachedSelector(
  state => state.data.collection,
  collection => collection
)(() => '')
```

Shouldn't this be default? If I remove the `() => ''`, I get an error. I know I could use the regular `reselect` `createSelector` method, but to uniformize my code, I'd rather user `re-reselect` everywhere.

**Comment by toomuchdesign** [comment]
Hi @augnustin, happy to see you around!

### Swapping arguments calls
I guess it's mainly a matter of tastes, and I wouldn't be able to justify such a breaking change to the current users.

### `state` as resolver (keySelector) argument
Using `state` argument to evaluate `resolver`'s value is not usual but I could come in handy is some special edge-scenario, just in case if some state property were needed for a better fine-tuning.

BTW, `re-reselect` stores internally a set of cached `reselect` selectors,  and `resolvers` only deal with how those selectors are cached. The generation of t**he actual value** returned to the user is completely **delegated to `reselect`**.

The only things the matters about `resolver` is their **returning value**.

### Make resolver (keySelector) optional
I considered this option in the past but I wasn't sure it how much worth it was.

In order to use `re-reselect` in the cases where no special selector caching is needed, we might think providing an **empty function call** to receive back a **normal `reselect` selector**.

```
export default createCachedSelector(
  state => state.data.collection,
  collection => collection
)()
```
I like `keySelector` name much more then the original `resolver`!

I stay open for any other clarification.
Greetings!
