### ISSUE TITLE
`recomputations` property for testing

### ISSUE THREAD

**Issue by olslash** [toomuchdesign/re-reselect#5]
Great lib -- seems like it should address a pain point in my app nicely.

like what's mentioned in https://github.com/reactjs/reselect#q-how-do-i-test-a-selector, i'd like to be able to test that my cached selectors are working like I expect. 

given the example code from the readme:

```javascript
const cachedSelector = createCachedSelector(
    (A, B, someArg) => expensiveComputation(A, B, someArg}),
)(
    (state, someArg) => someArg,
);

const fooSelector = cachedSelector(state, 'foo');
const barSelector = cachedSelector(state, 'bar');
```

I guess the API could look like:

```javascript
  cachedSelector.recomputations(state, 'foo')
```

What do you think?

**Comment by toomuchdesign** [comment]
Hi @olslash,
I wasn't aware of `createSelector`'s recomputation method!

Internally `re-reselect` calls standard`reselect` selector (by default) and returns its result.

Since you want to expose something more than the selector's result, It implies the need of extending the current API's.

What if we find a way to tell `re-reselect` to return the whole matching selector in place of its result?

In this way the user might be able to access any method/property exposed by the selector like `recomputation`, `resetRecomputations`, `resultFunc`, etc...

**Comment by olslash** [comment]
makes sense to me. let me try to put together a PR

**Comment by toomuchdesign** [comment]
[v0.2.0](https://github.com/toomuchdesign/re-reselect/releases/tag/v0.2.0) shipped!
@olslash It's been a pleasure collaborating with you.

**Comment by olslash** [comment]
Thanks again!
